version: '3'

tasks:

  # This command may require to be run with "sudo".
  # User should have $GOPATH/bin dir in $PATH.
  #
  # Additional resources:
  # - https://go.dev/doc/install
  # - https://protobuf.dev/getting-started/gotutorial/
  # - https://protobuf.dev/installation/
  # - https://go.dev/doc/tutorial/govulncheck
  # - https://docs.docker.com/reference/cli/docker/buildx/
  tools:
    desc: "Downloads all required tools required to develop project"
    deps: [install-go-vulnerability-check]
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - apt install -y protobuf-compiler

      # depending whether command was run with or without "sudo", it may
      # influence whether this step succeds. In case of error, please manually
      # check if tools are installed correctly (with or without "sudo" command)
      - protoc --version && govulncheck --version && protoc-gen-go --version

  install-go-vulnerability-check:
    desc: "Install Go vulnerability checking tool"
    internal: true
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  proto:
    desc: "Generates Go stubs from proto files"
    cmds:
      - git submodule update --init --recursive
      - protoc --go_out=. --go-grpc_out=. protobuf/messages.proto

  check-dependencies:
    desc: "Set the dependencies"
    cmds:
      - go mod tidy && go mod verify

  format:
    desc: "Apply formatting rules to Go code"
    cmds:
      - go fmt ./...

  lint:
    desc: "Apply linting to Go code"
    cmds:
      - go vet ./...

  unit-test:
    desc: "Run unit-tests"
    cmds:
      - go test ./... -cover

  vulnerability-check:
    desc: "Run vulnerability check"
    deps: [install-go-vulnerability-check]
    cmds:
      - govulncheck ./...

  build:
    desc: "Build example client CLI"
    deps: [format, lint]
    dir: ./cli
    cmds:
      - go build -o ./bin/go-client-cli cmd/client-cli/client-cli.go
    sources:
      - cmd/client-cli/client-cli.go
      - internal/**/*.go
      - ./*.go
      - go.mod
      - go.sum
    generates:
      - bin/go-client-cli

  build-docker:
    desc: "Builds the Docker image for the client app"
    vars:
      TAG: '{{.TAG| default "latest"}}'
    dotenv: ['.env']
    cmds:
      - docker buildx build -f ./cli/Dockerfile -t client_app_go:{{.TAG}} .

  delete:
    desc: "Delete binary artifacts"
    cmds:
      - rm cli/bin/*

  test-hash:
    deps: [build]
    desc: "Test hashing command with Default profile"
    cmds:
      - ./cli/bin/go-client-cli --profile=Default hash "Hello"

  test-sign:
    deps: [build]
    desc: "Test certificate signing command with Default profile"
    cmds:
      - ./cli/bin/go-client-cli --profile=Default sign ../crypto-broker-deployment/k8s/kube-broker/files/certificates/end-entity.csr ../crypto-broker-deployment/k8s/kube-broker/files/certificates/ca_cert.pem ../crypto-broker-deployment/k8s/kube-broker/files/certificates/private_key.pem

  ci:
    desc: "Runs local continuous integration checks on source code"
    cmds:
      - task: check-dependencies
      - task: format
      - task: lint
      - task: unit-test
      - task: vulnerability-check
